### ISSUE TITLE
Test failures with sparse 0.15.0

### ISSUE THREAD

**Issue by khaeru** [khaeru/genno#113]
Comparing [run A](https://github.com/khaeru/genno/actions/runs/7456879781/job/20296269624#step:5:562) with [run B](https://github.com/khaeru/genno/actions/runs/7470564374/job/20329469523#step:5:564), the update to sparse 0.15.0 caused numerous failures due to:

```
AttributeError: module 'sparse' has no attribute 'astype'
AttributeError: module 'sparse' has no attribute 'broadcast_to'
AttributeError: module 'sparse' has no attribute 'concat'
AttributeError: module 'sparse' has no attribute 'isnan'
```
…all via xarray.core.duck_array_ops.

These appear to be noted at pydata/xarray#8602 and pydata/sparse#622.

**Fix**
Upstream: pydata/sparse#623, which I guess will get released with the next version of sparse, for instance 0.15.1

**Mitigation**
- Don't use genno with sparse 0.15.0; maybe add this to pyproject.toml.
- Temporarily exclude sparse 0.15.0 from genno CI.

**Comment by khaeru** [comment]
Sparse 0.15.0 also appears to have added COO.squeeze() (pydata/sparse#613).

Thus also TODO:
- Drop the corresponding method from SparseDataArray: https://github.com/khaeru/genno/blob/1b49e22f827f261f9b516819d31a5b2d6eeaf28c/genno/core/sparsedataarray.py#L256-L259
- Perhaps add 'monitoring' tests to check that "vanilla" sparse-backed xr.DataArray does not provide certain features needed by genno. If any of these switch from XFAIL to XPASS in the future, then the corresponding pieces of SparseDataArray can be discarded.

**Comment by hameerabbasi** [comment]
0.15.1 is released.

**Comment by khaeru** [comment]
Super quick! Thanks so much.
