### ISSUE TITLE
Cache based on function code / document caching based on file contents

### ISSUE THREAD

**Issue by phackstock** [khaeru/genno#49]
(Transferred from the discussion of https://github.com/iiasa/message-ix-models/issues/25.)

The main question is whether genno covers the following two features in its caching option which are covered by an implementation I recently did using [`joblib.Memory`](https://joblib.readthedocs.io/en/latest/generated/joblib.Memory.html).

1. joblib.Memory doesn't only cache the input values but also the function code itself. This way if your function code change but the input stays the same it won't be tricked into wrongly thinking that it has the results cached already. 
2. My usecase involved reading data from a file, doing some computation and providing the result as a pandas dataframe. I provide the function with a filename in form of a `pathlib.Path` or a `str`. That means my function now looks like this: `read_and_compute_some_data(file: Union[str, pathlib.Path], ...) -> pd.DataFrame`. Here the `joblib.Memory` caching decorator would simply save a hash of the **name** of the input file. In some way that's a problem since I'm not actually interested in the name of my datafile but the **contents**.  For this I have created a small wrapper class `InputFile` for the filename which stores a hash of the files contents. As joblib uses pickle to serialize the data to binary I have modified the way `InputFile` is serialized by just considering the contents of the file and not the name.

Minimum working example of caching of the **content** of input files using `joblib.Memory`:
```python

from joblib import Memory
from pathlib import Path
import hashlib
import pandas as pd

# setting the directory of the cache in the parent folder of the file
memory = Memory(Path(__file__).parent / ".joblib_cache") 

class InputFile:
    def __init__(self, file) -> None:
        self.file = file
        self.hash = self.calc_hash()

    def calc_hash(self) -> str:
        """Generate a hash from the contents of a file

        Parameters
        ----------
        file : str
            File to be hashed

        Returns
        -------
        str:
            Hexadecimal representation of the file hash

        Notes
        -----
        For details refer to https://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python
        """
        with open(self.file, "rb") as f:
            file_hash = hashlib.md5()
            # we read the file at a rate of 8192 bytes a chunk
            # this takes advantage of the digest size of 128 bytes
            while chunk := f.read(8192):
                file_hash.update(chunk)
        return file_hash.hexdigest()

    def __getstate__(self) -> dict:
        """Custom __getstate__ function for using with Memory.cache from joblib.Memory

        Returns
        -------
        dict
            __dict__ minus the file name

        Notes
        -----
        """
        # this is to 'trick' pickle into only considering the hash of the contents
        # of the file and not the filename itself when checking if the have 
        # cached results. Of course you could also change it to include the filename
        # as well. A good way might be use both the filename (just the name
        # and not the entire path) and the hash of the contents. This would possibly
        # also make the cache independent of the user as it would no longer hash
        # the directory structure where the file is stored

        state = self.__dict__.copy()
        # remove the file from the state as we are just interested in the contents
        del state["file"]
        return state

    def __repr__(self) -> str:
        # this is just so that we get a nice representation of the class since 
        # joblib.memory also writes a json with with the input parameters of
        # the function call
        return f"{self.__class__}: {self.__dict__}"

# adding the decorator to make read_from_file cache-able 
# also caching this might be a bit pointless but I think it illustrates 
# the general layout of such a function
@memory.cache
def read_from_file(input_file):
    return pd.read_csv(input_file.file)

if __name__ == "__main__":
    # in the current configuration the second call read_from_file would hit the cache if the contents of file1.csv and file2.csv
    # are the same even though they have different names. 
    read_from_file(InputFile("file1.csv"))
    read_from_file(InputFile("file2.csv"))
```

Additionally, joblib.Memory also saves json files where the input values are stored which is a nice feature for book keeping.

**Comment by khaeru** [comment]
Thanks for this example of prior art, one that I wasn't aware of! It does seem similar in many ways.

> 1. joblib.Memory doesn't only cache the input values but also the function code itself. This way if your function code change but the input stays the same it won't be tricked into wrongly thinking that it has the results cached already.

Peeking at the code, it seems like joblib always caches the code of the decorated function, and then it retrieves and compares the cached code as a second check on cache matching.

genno does not do this, but it would be a nice enhancement. I think a simpler way to implement it would be to use [`inspect.getmembers`](https://docs.python.org/3/library/inspect.html#inspect.getmembers) and include the code in the cache key, i.e. among the items given to `arg_hash()`: https://github.com/khaeru/genno/blob/f9fbfd8cd613b0c8a2221ecd77a9966dbe170eaf/genno/caching.py#L57

> 2. […] Here the `joblib.Memory` caching decorator would simply save a hash of the **name** of the input file. In some way that's a problem since I'm not actually interested in the name of my datafile but the **contents**.

The hashing approach is nice. In some cases—for instance, the IEA data referenced in iiasa/message-ix-models#25—I worry that _even hashing the file_ is an expensive step. I checked one file about 780 MB, and even the command-line `sha1sum` tool takes about 10 seconds.

Somewhere (I forget where) I used [`Path.stat()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat) and passed this to the loading function as an unused argument:
```py
from pathlib import Path

@cache
def load_func(path, *extra):
    # `extra` args are unused, but affect the cache key
    return pd.read_csv(path)

baz = Path("foo", "bar", "baz.txt")

load_func(baz, baz.stat().mtime)

# Different args → different key → function will run again
load_func(baz, baz.stat().mtime + 1)
```
In some cases this is sufficient to identify when a file has changed.

One can also hash the entire file, without modifying the function:
```py
from hashlib import blake2b

load_func(baz, blake2b(baz.read_bytes()).hexdigest())
```

I can definitely add both of these as examples in the documentation.
